[package]
name = "test-yew-app"
version = "0.1.0"
authors = ["James <geekylink@gekinzuku.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew-router = "0.14.0"
yew = "0.17.0"
